services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: on-failure
    env_file:
      - .env
    volumes:
      - my_mariadb:/var/lib/mysql
    networks:
      - inceptionNet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: on-failure
    env_file:
      - .env
    volumes:
      - my_wordpress:/var/www/html
    networks:
      - inceptionNet
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "php-fpm82 -t || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - my_wordpress:/var/www/html
    networks:
      - inceptionNet
    depends_on:
      wordpress:
        condition: service_healthy

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: on-failure
    env_file:
      - .env
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
      - PMA_PORT=3306
    ports:
      - "8080:80"
    networks:
      - inceptionNet
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  my_mariadb:
    driver: local
  my_wordpress:
    driver: local

networks:
  inceptionNet:
    driver: bridge