---
# Database Configuration
db_host: "{{ lookup('env', 'DB_HOST') | default('localhost') }}"
db_name: "{{ lookup('env', 'DB_NAME') | default('inception') }}"
db_user: "{{ lookup('env', 'DB_USER') | default('odakhch') }}"
db_password: "{{ lookup('env', 'DB_PASSWORD') | default('SecureDB_Pass123!') }}"
db_root_password: "{{ lookup('env', 'DB_ROOT_PASSWORD') | default('SecureRoot_Pass456!') }}"

# WordPress Configuration
wp_root_user: "{{ lookup('env', 'WP_ROOT_USER') | default('oussamadakhch') }}"
wp_root_password: "{{ lookup('env', 'WP_ROOT_PASSWORD') | default('AdminWP_Pass789!') }}"
wp_root_email: "{{ lookup('env', 'WP_ROOT_EMAIL') | default('odakhch@student.1337.ma') }}"
wp_user: "{{ lookup('env', 'WP_USER') | default('oussama') }}"
wp_password: "{{ lookup('env', 'WP_PASSWORD') | default('AuthorWP_Pass321!') }}"
wp_user_email: "{{ lookup('env', 'WP_USER_EMAIL') | default('odakhch@gmail.com') }}"
wp_title: "{{ lookup('env', 'WP_TITLE') | default('Inception') }}"
wp_url: "{{ lookup('env', 'WP_URL') | default('https://marinadberr.duckdns.org') }}"

# Domain Configuration
domain_name: "{{ lookup('env', 'DOMAIN_NAME') | default('marinadberr.duckdns.org') }}"
