[webservers]
ec2_instance ansible_host=98.81.72.111 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/your-key.pem ansible_python_interpreter=/usr/bin/python3

[webservers:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'